apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  completions: 4 # first pod completes - second pod created
  ttlSecondsAfterFinished: 100
  parallelism: 2 # creates two pods in parallel
  backoffLimit: 15 # number of retries before the job is marked as failed
  template:
    spec:
      containers:
        - name: pi
          image: perl
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
