apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-replicaset
  annotations:
    buildVersion: "1.2"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: mypc
      hostname: headless-service-hostname
      subdomain: pod-subdomain-name
