apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-rc
spec:
  replicas: 3
  selector:
    app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
